import type {
  User,
  Workspace,
  Project,
  AuditLog,
  Document,
  UserStory,
  TestSuite,
  TestCase,
  TestRun,
  Notification,
  ProjectMember,
} from "./types"

export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "admin@sdlc.io",
    name: "Alex Admin",
    role: "admin",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1", "proj-2"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "user-3",
    email: "peter@sdlc.io",
    name: "Peter PM",
    role: "pm",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1", "proj-2"],
    createdAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "user-4",
    email: "bella@sdlc.io",
    name: "Bella BA",
    role: "ba",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "user-5",
    email: "quinn@sdlc.io",
    name: "Quinn QA",
    role: "qa",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1", "proj-2"],
    createdAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "user-6",
    email: "david@sdlc.io",
    name: "David Dev",
    role: "developer",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-03-15T00:00:00Z",
  },
  {
    id: "user-7",
    email: "michael.brown@sdlc.io",
    name: "Michael Brown",
    role: "developer",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-03-20T00:00:00Z",
  },
  {
    id: "user-8",
    email: "sarah.johnson@sdlc.io",
    name: "Sarah Johnson",
    role: "qa",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-03-25T00:00:00Z",
  },
  {
    id: "user-9",
    email: "robert.davis@sdlc.io",
    name: "Robert Davis",
    role: "pm",
    status: "inactive",
    workspaceIds: ["ws-1"],
    assignedProjectIds: [],
    createdAt: "2024-04-01T00:00:00Z",
  },
  {
    id: "user-10",
    email: "emily.wilson@sdlc.io",
    name: "Emily Wilson",
    role: "ba",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1", "proj-2"],
    createdAt: "2024-04-05T00:00:00Z",
  },
  {
    id: "user-11",
    email: "james.miller@sdlc.io",
    name: "James Miller",
    role: "developer",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-04-10T00:00:00Z",
  },
  {
    id: "user-12",
    email: "jennifer.taylor@sdlc.io",
    name: "Jennifer Taylor",
    role: "qa",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-04-15T00:00:00Z",
  },
  {
    id: "user-13",
    email: "william.anderson@sdlc.io",
    name: "William Anderson",
    role: "developer",
    status: "inactive",
    workspaceIds: ["ws-1"],
    assignedProjectIds: [],
    createdAt: "2024-04-20T00:00:00Z",
  },
  {
    id: "user-14",
    email: "linda.thomas@sdlc.io",
    name: "Linda Thomas",
    role: "pm",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-04-25T00:00:00Z",
  },
  {
    id: "user-15",
    email: "charles.jackson@sdlc.io",
    name: "Charles Jackson",
    role: "ba",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "user-16",
    email: "patricia.white@sdlc.io",
    name: "Patricia White",
    role: "qa",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1", "proj-2"],
    createdAt: "2024-05-05T00:00:00Z",
  },
  {
    id: "user-17",
    email: "mark.harris@sdlc.io",
    name: "Mark Harris",
    role: "developer",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-05-10T00:00:00Z",
  },
  {
    id: "user-18",
    email: "barbara.martin@sdlc.io",
    name: "Barbara Martin",
    role: "admin",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1", "proj-2"],
    createdAt: "2024-05-15T00:00:00Z",
  },
  {
    id: "user-19",
    email: "richard.garcia@sdlc.io",
    name: "Richard Garcia",
    role: "pm",
    status: "inactive",
    workspaceIds: ["ws-1"],
    assignedProjectIds: [],
    createdAt: "2024-05-20T00:00:00Z",
  },
  {
    id: "user-20",
    email: "karen.rodriguez@sdlc.io",
    name: "Karen Rodriguez",
    role: "ba",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-05-25T00:00:00Z",
  },
  {
    id: "user-21",
    email: "thomas.lee@sdlc.io",
    name: "Thomas Lee",
    role: "developer",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "user-22",
    email: "nancy.perez@sdlc.io",
    name: "Nancy Perez",
    role: "qa",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1", "proj-2"],
    createdAt: "2024-06-05T00:00:00Z",
  },
  {
    id: "user-23",
    email: "steven.scott@sdlc.io",
    name: "Steven Scott",
    role: "developer",
    status: "inactive",
    workspaceIds: ["ws-1"],
    assignedProjectIds: [],
    createdAt: "2024-06-10T00:00:00Z",
  },
  {
    id: "user-24",
    email: "dorothy.green@sdlc.io",
    name: "Dorothy Green",
    role: "pm",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-06-15T00:00:00Z",
  },
  {
    id: "user-25",
    email: "paul.adams@sdlc.io",
    name: "Paul Adams",
    role: "ba",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-06-20T00:00:00Z",
  },
  {
    id: "user-26",
    email: "betty.nelson@sdlc.io",
    name: "Betty Nelson",
    role: "qa",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-06-25T00:00:00Z",
  },
  {
    id: "user-27",
    email: "daniel.carter@sdlc.io",
    name: "Daniel Carter",
    role: "developer",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-07-01T00:00:00Z",
  },
  {
    id: "user-28",
    email: "susan.roberts@sdlc.io",
    name: "Susan Roberts",
    role: "admin",
    status: "inactive",
    workspaceIds: ["ws-1"],
    assignedProjectIds: [],
    createdAt: "2024-07-05T00:00:00Z",
  },
  {
    id: "user-29",
    email: "matthew.phillips@sdlc.io",
    name: "Matthew Phillips",
    role: "pm",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1", "proj-2"],
    createdAt: "2024-07-10T00:00:00Z",
  },
  {
    id: "user-30",
    email: "jessica.campbell@sdlc.io",
    name: "Jessica Campbell",
    role: "ba",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-07-15T00:00:00Z",
  },
  {
    id: "user-31",
    email: "anthony.parker@sdlc.io",
    name: "Anthony Parker",
    role: "qa",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-07-20T00:00:00Z",
  },
  {
    id: "user-32",
    email: "sandra.evans@sdlc.io",
    name: "Sandra Evans",
    role: "developer",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-07-25T00:00:00Z",
  },
  {
    id: "user-33",
    email: "donald.edwards@sdlc.io",
    name: "Donald Edwards",
    role: "pm",
    status: "inactive",
    workspaceIds: ["ws-1"],
    assignedProjectIds: [],
    createdAt: "2024-08-01T00:00:00Z",
  },
  {
    id: "user-34",
    email: "ashley.collins@sdlc.io",
    name: "Ashley Collins",
    role: "ba",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-08-05T00:00:00Z",
  },
  {
    id: "user-35",
    email: "kevin.stewart@sdlc.io",
    name: "Kevin Stewart",
    role: "qa",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1", "proj-2"],
    createdAt: "2024-08-10T00:00:00Z",
  },
  {
    id: "user-36",
    email: "kimberly.sanchez@sdlc.io",
    name: "Kimberly Sanchez",
    role: "developer",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-08-15T00:00:00Z",
  },
  {
    id: "user-37",
    email: "edward.morris@sdlc.io",
    name: "Edward Morris",
    role: "admin",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1", "proj-2"],
    createdAt: "2024-08-20T00:00:00Z",
  },
  {
    id: "user-38",
    email: "donna.rogers@sdlc.io",
    name: "Donna Rogers",
    role: "pm",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-08-25T00:00:00Z",
  },
  {
    id: "user-39",
    email: "ryan.reed@sdlc.io",
    name: "Ryan Reed",
    role: "ba",
    status: "inactive",
    workspaceIds: ["ws-1"],
    assignedProjectIds: [],
    createdAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "user-40",
    email: "michelle.cook@sdlc.io",
    name: "Michelle Cook",
    role: "qa",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-09-05T00:00:00Z",
  },
  {
    id: "user-41",
    email: "gary.morgan@sdlc.io",
    name: "Gary Morgan",
    role: "developer",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-09-10T00:00:00Z",
  },
  {
    id: "user-42",
    email: "barbara.bell@sdlc.io",
    name: "Barbara Bell",
    role: "pm",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-09-15T00:00:00Z",
  },
  {
    id: "user-43",
    email: "stephen.murphy@sdlc.io",
    name: "Stephen Murphy",
    role: "ba",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-09-20T00:00:00Z",
  },
  {
    id: "user-44",
    email: "deborah.bailey@sdlc.io",
    name: "Deborah Bailey",
    role: "qa",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1", "proj-2"],
    createdAt: "2024-09-25T00:00:00Z",
  },
  {
    id: "user-45",
    email: "jason.rivera@sdlc.io",
    name: "Jason Rivera",
    role: "developer",
    status: "inactive",
    workspaceIds: ["ws-1"],
    assignedProjectIds: [],
    createdAt: "2024-10-01T00:00:00Z",
  },
  {
    id: "user-46",
    email: "margaret.cooper@sdlc.io",
    name: "Margaret Cooper",
    role: "admin",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-10-05T00:00:00Z",
  },
  {
    id: "user-47",
    email: "dennis.richardson@sdlc.io",
    name: "Dennis Richardson",
    role: "pm",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-10-10T00:00:00Z",
  },
  {
    id: "user-48",
    email: "carol.cox@sdlc.io",
    name: "Carol Cox",
    role: "ba",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1", "proj-2"],
    createdAt: "2024-10-15T00:00:00Z",
  },
  {
    id: "user-49",
    email: "jerry.howard@sdlc.io",
    name: "Jerry Howard",
    role: "qa",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-10-20T00:00:00Z",
  },
  {
    id: "user-50",
    email: "christine.ward@sdlc.io",
    name: "Christine Ward",
    role: "developer",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-10-25T00:00:00Z",
  },
  {
    id: "user-51",
    email: "frank.torres@sdlc.io",
    name: "Frank Torres",
    role: "pm",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-11-01T00:00:00Z",
  },
  {
    id: "user-52",
    email: "ann.peterson@sdlc.io",
    name: "Ann Peterson",
    role: "ba",
    status: "inactive",
    workspaceIds: ["ws-1"],
    assignedProjectIds: [],
    createdAt: "2024-11-05T00:00:00Z",
  },
  {
    id: "user-53",
    email: "charles.gray@sdlc.io",
    name: "Charles Gray",
    role: "qa",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-11-10T00:00:00Z",
  },
  {
    id: "user-54",
    email: "brenda.ramirez@sdlc.io",
    name: "Brenda Ramirez",
    role: "developer",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1", "proj-2"],
    createdAt: "2024-11-15T00:00:00Z",
  },
  {
    id: "user-55",
    email: "samuel.james@sdlc.io",
    name: "Samuel James",
    role: "admin",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-1"],
    createdAt: "2024-11-20T00:00:00Z",
  },
  {
    id: "user-56",
    email: "diane.watson@sdlc.io",
    name: "Diane Watson",
    role: "pm",
    status: "active",
    workspaceIds: ["ws-1"],
    assignedProjectIds: ["proj-2"],
    createdAt: "2024-11-25T00:00:00Z",
  },
]

export const mockWorkspaces: Workspace[] = [
  {
    id: "ws-1",
    name: "Acme Corporation",
    slug: "acme-corp",
    ownerId: "user-1",
    memberIds: [
      "user-1",
      "user-3",
      "user-4",
      "user-5",
      "user-6",
      "user-7",
      "user-8",
      "user-9",
      "user-10",
      "user-11",
      "user-12",
      "user-13",
      "user-14",
      "user-15",
      "user-16",
      "user-17",
      "user-18",
      "user-19",
      "user-20",
      "user-21",
      "user-22",
      "user-23",
      "user-24",
      "user-25",
      "user-26",
      "user-27",
      "user-28",
      "user-29",
      "user-30",
      "user-31",
      "user-32",
      "user-33",
      "user-34",
      "user-35",
      "user-36",
      "user-37",
      "user-38",
      "user-39",
      "user-40",
      "user-41",
      "user-42",
      "user-43",
      "user-44",
      "user-45",
      "user-46",
      "user-47",
      "user-48",
      "user-49",
      "user-50",
      "user-51",
      "user-52",
      "user-53",
      "user-54",
      "user-55",
      "user-56",
    ],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "ws-2",
    name: "TechStart Inc",
    slug: "techstart",
    ownerId: "user-1",
    memberIds: ["user-1", "user-3"],
    createdAt: "2024-06-01T00:00:00Z",
  },
]

export const mockProjects: Project[] = [
  {
    id: "proj-1",
    name: "E-Commerce Platform v2",
    description: "Complete redesign and rebuild of the e-commerce platform with AI-powered recommendations",
    workspaceId: "ws-1",
    managerId: "user-3", // Changed from "user-1" (Admin) to "user-3" (Peter PM)
    status: "active",
    teamIds: [
      "user-1",
      "user-3",
      "user-4",
      "user-5",
      "user-6",
      "user-7",
      "user-8",
      "user-9",
      "user-10",
      "user-11",
      "user-12",
      "user-13",
      "user-14",
      "user-15",
      "user-16",
      "user-17",
      "user-18",
      "user-19",
      "user-20",
      "user-21",
      "user-22",
      "user-23",
      "user-24",
      "user-25",
      "user-26",
      "user-27",
      "user-28",
      "user-29",
      "user-30",
      "user-31",
      "user-32",
      "user-33",
      "user-34",
      "user-35",
      "user-36",
      "user-37",
      "user-38",
      "user-39",
      "user-40",
      "user-41",
      "user-42",
      "user-43",
      "user-44",
      "user-45",
      "user-46",
      "user-47",
      "user-48",
      "user-49",
      "user-50",
      "user-51",
      "user-52",
      "user-53",
      "user-54",
      "user-55",
      "user-56",
    ],
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-12-10T00:00:00Z",
  },
  {
    id: "proj-1-frontend",
    name: "Frontend Development",
    description: "React/Next.js frontend implementation with responsive design",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-3", // Already correct (Peter PM)
    status: "active",
    teamIds: ["user-1", "user-3", "user-4", "user-6", "user-7", "user-8"],
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2024-12-05T00:00:00Z",
  },
  {
    id: "proj-1-backend",
    name: "Backend Development",
    description: "Node.js/Express backend with microservices architecture",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-14", // Changed from "user-5" (QA) to "user-14" (Linda Thomas - PM)
    status: "active",
    teamIds: ["user-1", "user-3", "user-5", "user-9", "user-10", "user-11", "user-12"],
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2024-12-08T00:00:00Z",
  },
  {
    id: "proj-1-qa",
    name: "QA & Testing",
    description: "Comprehensive testing strategy including automated and manual testing",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-24", // Changed from "user-13" (no role match) to "user-24" (Dorothy Green - PM)
    status: "active",
    teamIds: ["user-1", "user-3", "user-5", "user-13", "user-14", "user-15"],
    createdAt: "2024-03-20T00:00:00Z",
    updatedAt: "2024-12-09T00:00:00Z",
  },
  {
    id: "proj-2",
    name: "Mobile Banking App",
    description: "New mobile banking application with biometric authentication and real-time notifications",
    workspaceId: "ws-1",
    managerId: "user-29", // Changed from "user-7" (Developer) to "user-29" (Matthew Phillips - PM)
    status: "active",
    teamIds: [
      "user-1",
      "user-3",
      "user-5",
      "user-7",
      "user-8",
      "user-9",
      "user-10",
      "user-11",
      "user-12",
      "user-13",
      "user-14",
      "user-15",
      "user-16",
      "user-17",
      "user-18",
      "user-19",
      "user-20",
      "user-21",
      "user-22",
      "user-23",
      "user-24",
      "user-25",
      "user-26",
      "user-27",
      "user-28",
      "user-29",
      "user-30",
      "user-31",
      "user-32",
      "user-33",
      "user-34",
      "user-35",
      "user-36",
      "user-37",
      "user-38",
      "user-39",
      "user-40",
      "user-41",
      "user-42",
      "user-43",
      "user-44",
      "user-45",
      "user-46",
      "user-47",
      "user-48",
      "user-49",
      "user-50",
      "user-51",
      "user-52",
      "user-53",
      "user-54",
      "user-55",
      "user-56",
    ],
    createdAt: "2024-06-15T00:00:00Z",
    updatedAt: "2024-12-08T00:00:00Z",
  },
  {
    id: "proj-2-ios",
    name: "iOS Development",
    description: "Native iOS app development using Swift",
    workspaceId: "ws-1",
    parentProjectId: "proj-2",
    managerId: "user-38", // Changed from "user-16" (no PM role) to "user-38" (Donna Rogers - PM)
    status: "active",
    teamIds: ["user-1", "user-3", "user-7", "user-16", "user-17", "user-18"],
    createdAt: "2024-06-20T00:00:00Z",
    updatedAt: "2024-12-07T00:00:00Z",
  },
  {
    id: "proj-2-android",
    name: "Android Development",
    description: "Native Android app development using Kotlin",
    workspaceId: "ws-1",
    parentProjectId: "proj-2",
    managerId: "user-47", // Changed from "user-16" (no PM role) to "user-47" (Dennis Richardson - PM)
    status: "active",
    teamIds: ["user-1", "user-3", "user-7", "user-16", "user-17", "user-18"],
    createdAt: "2024-06-20T00:00:00Z",
    updatedAt: "2024-12-07T00:00:00Z",
  },
  {
    id: "proj-1-sub-5",
    name: "API Gateway Implementation",
    description: "Central API gateway for routing and rate limiting",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-38",
    status: "active",
    teamIds: ["user-3", "user-9", "user-10", "user-11"],
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-12-09T00:00:00Z",
  },
  {
    id: "proj-1-sub-6",
    name: "Database Optimization",
    description: "Performance tuning and indexing for PostgreSQL",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-29",
    status: "active",
    teamIds: ["user-3", "user-10", "user-11"],
    createdAt: "2024-04-05T00:00:00Z",
    updatedAt: "2024-12-08T00:00:00Z",
  },
  {
    id: "proj-1-sub-7",
    name: "Authentication System",
    description: "OAuth 2.0 and JWT implementation",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-42",
    status: "active",
    teamIds: ["user-3", "user-9", "user-12"],
    createdAt: "2024-04-10T00:00:00Z",
    updatedAt: "2024-12-07T00:00:00Z",
  },
  {
    id: "proj-1-sub-8",
    name: "Payment Integration",
    description: "Stripe and PayPal integration",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-47",
    status: "active",
    teamIds: ["user-3", "user-10", "user-13"],
    createdAt: "2024-04-15T00:00:00Z",
    updatedAt: "2024-12-06T00:00:00Z",
  },
  {
    id: "proj-1-sub-9",
    name: "Search Engine Implementation",
    description: "Elasticsearch integration for product search",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-51",
    status: "active",
    teamIds: ["user-3", "user-11", "user-12"],
    createdAt: "2024-04-20T00:00:00Z",
    updatedAt: "2024-12-05T00:00:00Z",
  },
  {
    id: "proj-1-sub-10",
    name: "Caching Layer",
    description: "Redis caching implementation",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-56",
    status: "active",
    teamIds: ["user-3", "user-9", "user-11"],
    createdAt: "2024-04-25T00:00:00Z",
    updatedAt: "2024-12-04T00:00:00Z",
  },
  {
    id: "proj-1-sub-11",
    name: "Mobile App - iOS",
    description: "Native iOS app development with SwiftUI",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-14",
    status: "active",
    teamIds: ["user-3", "user-7", "user-8"],
    createdAt: "2024-05-01T00:00:00Z",
    updatedAt: "2024-12-03T00:00:00Z",
  },
  {
    id: "proj-1-sub-12",
    name: "Mobile App - Android",
    description: "Native Android app development with Kotlin",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-24",
    status: "active",
    teamIds: ["user-3", "user-7", "user-8"],
    createdAt: "2024-05-05T00:00:00Z",
    updatedAt: "2024-12-02T00:00:00Z",
  },
  {
    id: "proj-1-sub-13",
    name: "Admin Dashboard",
    description: "Comprehensive admin panel for system management",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-29",
    status: "active",
    teamIds: ["user-3", "user-6", "user-7"],
    createdAt: "2024-05-10T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "proj-1-sub-14",
    name: "Analytics Service",
    description: "Real-time analytics and reporting",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-38",
    status: "active",
    teamIds: ["user-3", "user-11", "user-12"],
    createdAt: "2024-05-15T00:00:00Z",
    updatedAt: "2024-11-30T00:00:00Z",
  },
  {
    id: "proj-1-sub-15",
    name: "Email Service",
    description: "Email notifications and marketing campaigns",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-42",
    status: "active",
    teamIds: ["user-3", "user-9", "user-10"],
    createdAt: "2024-05-20T00:00:00Z",
    updatedAt: "2024-11-29T00:00:00Z",
  },
  {
    id: "proj-1-sub-16",
    name: "Push Notifications",
    description: "Push notification system for mobile apps",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-47",
    status: "active",
    teamIds: ["user-3", "user-10", "user-11"],
    createdAt: "2024-05-25T00:00:00Z",
    updatedAt: "2024-11-28T00:00:00Z",
  },
  {
    id: "proj-1-sub-17",
    name: "CDN Implementation",
    description: "CloudFront CDN for static assets",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-51",
    status: "active",
    teamIds: ["user-3", "user-9", "user-12"],
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: "2024-11-27T00:00:00Z",
  },
  {
    id: "proj-1-sub-18",
    name: "Monitoring & Logging",
    description: "ELK stack for centralized logging",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-56",
    status: "active",
    teamIds: ["user-3", "user-11", "user-12"],
    createdAt: "2024-06-05T00:00:00Z",
    updatedAt: "2024-11-26T00:00:00Z",
  },
  {
    id: "proj-1-sub-19",
    name: "Disaster Recovery",
    description: "Backup and recovery strategy",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-14",
    status: "active",
    teamIds: ["user-3", "user-10", "user-11"],
    createdAt: "2024-06-10T00:00:00Z",
    updatedAt: "2024-11-25T00:00:00Z",
  },
  {
    id: "proj-1-sub-20",
    name: "Performance Testing",
    description: "Load testing and performance optimization",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-24",
    status: "active",
    teamIds: ["user-3", "user-5", "user-13"],
    createdAt: "2024-06-15T00:00:00Z",
    updatedAt: "2024-11-24T00:00:00Z",
  },
  {
    id: "proj-1-sub-21",
    name: "Security Audit",
    description: "Penetration testing and security review",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-29",
    status: "active",
    teamIds: ["user-3", "user-9", "user-14"],
    createdAt: "2024-06-20T00:00:00Z",
    updatedAt: "2024-11-23T00:00:00Z",
  },
  {
    id: "proj-1-sub-22",
    name: "Documentation Portal",
    description: "API documentation and user guides",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-38",
    status: "active",
    teamIds: ["user-3", "user-6", "user-7"],
    createdAt: "2024-06-25T00:00:00Z",
    updatedAt: "2024-11-22T00:00:00Z",
  },
  {
    id: "proj-1-sub-23",
    name: "Developer Tools",
    description: "SDK and CLI tools for developers",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-42",
    status: "active",
    teamIds: ["user-3", "user-9", "user-11"],
    createdAt: "2024-07-01T00:00:00Z",
    updatedAt: "2024-11-21T00:00:00Z",
  },
  {
    id: "proj-1-sub-24",
    name: "Integration Testing",
    description: "End-to-end integration tests",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-47",
    status: "active",
    teamIds: ["user-3", "user-5", "user-13"],
    createdAt: "2024-07-05T00:00:00Z",
    updatedAt: "2024-11-20T00:00:00Z",
  },
  {
    id: "proj-1-sub-25",
    name: "Compliance Review",
    description: "GDPR and compliance audit",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-51",
    status: "active",
    teamIds: ["user-3", "user-14", "user-15"],
    createdAt: "2024-07-10T00:00:00Z",
    updatedAt: "2024-11-19T00:00:00Z",
  },
  {
    id: "proj-1-sub-26",
    name: "Migration Planning",
    description: "Data migration strategy",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-56",
    status: "active",
    teamIds: ["user-3", "user-10", "user-12"],
    createdAt: "2024-07-15T00:00:00Z",
    updatedAt: "2024-11-18T00:00:00Z",
  },
  {
    id: "proj-1-sub-27",
    name: "Training Program",
    description: "User training and onboarding",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-14",
    status: "active",
    teamIds: ["user-3", "user-6", "user-15"],
    createdAt: "2024-07-20T00:00:00Z",
    updatedAt: "2024-11-17T00:00:00Z",
  },
  {
    id: "proj-1-sub-28",
    name: "Support System Setup",
    description: "Customer support infrastructure",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-24",
    status: "active",
    teamIds: ["user-3", "user-7", "user-14"],
    createdAt: "2024-07-25T00:00:00Z",
    updatedAt: "2024-11-16T00:00:00Z",
  },
  {
    id: "proj-1-sub-29",
    name: "Feedback System",
    description: "User feedback and survey collection",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-29",
    status: "active",
    teamIds: ["user-3", "user-9", "user-10"],
    createdAt: "2024-08-01T00:00:00Z",
    updatedAt: "2024-11-15T00:00:00Z",
  },
  {
    id: "proj-1-sub-30",
    name: "Beta Testing",
    description: "Beta program management",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-38",
    status: "active",
    teamIds: ["user-3", "user-5", "user-13"],
    createdAt: "2024-08-05T00:00:00Z",
    updatedAt: "2024-11-14T00:00:00Z",
  },
  {
    id: "proj-1-sub-31",
    name: "Release Management",
    description: "Release planning and deployment",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-42",
    status: "active",
    teamIds: ["user-3", "user-9", "user-11"],
    createdAt: "2024-08-10T00:00:00Z",
    updatedAt: "2024-11-13T00:00:00Z",
  },
  {
    id: "proj-1-sub-32",
    name: "DevOps Pipeline",
    description: "CI/CD pipeline setup and maintenance",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-47",
    status: "active",
    teamIds: ["user-3", "user-10", "user-11"],
    createdAt: "2024-08-15T00:00:00Z",
    updatedAt: "2024-11-12T00:00:00Z",
  },
  {
    id: "proj-1-sub-33",
    name: "Infrastructure Code",
    description: "Infrastructure as Code (Terraform)",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-51",
    status: "active",
    teamIds: ["user-3", "user-11", "user-12"],
    createdAt: "2024-08-20T00:00:00Z",
    updatedAt: "2024-11-11T00:00:00Z",
  },
  {
    id: "proj-1-sub-34",
    name: "Container Orchestration",
    description: "Kubernetes setup and configuration",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-56",
    status: "active",
    teamIds: ["user-3", "user-9", "user-12"],
    createdAt: "2024-08-25T00:00:00Z",
    updatedAt: "2024-11-10T00:00:00Z",
  },
  {
    id: "proj-1-sub-35",
    name: "Microservices Refactor",
    description: "Monolith to microservices migration",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-14",
    status: "active",
    teamIds: ["user-3", "user-10", "user-11"],
    createdAt: "2024-09-01T00:00:00Z",
    updatedAt: "2024-11-09T00:00:00Z",
  },
  {
    id: "proj-1-sub-36",
    name: "GraphQL API",
    description: "GraphQL API implementation",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-24",
    status: "active",
    teamIds: ["user-3", "user-9", "user-11"],
    createdAt: "2024-09-05T00:00:00Z",
    updatedAt: "2024-11-08T00:00:00Z",
  },
  {
    id: "proj-1-sub-37",
    name: "Webhooks System",
    description: "Event-based webhook system",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-29",
    status: "active",
    teamIds: ["user-3", "user-10", "user-12"],
    createdAt: "2024-09-10T00:00:00Z",
    updatedAt: "2024-11-07T00:00:00Z",
  },
  {
    id: "proj-1-sub-38",
    name: "Rate Limiting",
    description: "API rate limiting and throttling",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-38",
    status: "active",
    teamIds: ["user-3", "user-9", "user-11"],
    createdAt: "2024-09-15T00:00:00Z",
    updatedAt: "2024-11-06T00:00:00Z",
  },
  {
    id: "proj-1-sub-39",
    name: "Multi-Tenancy",
    description: "Multi-tenant architecture implementation",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-42",
    status: "active",
    teamIds: ["user-3", "user-11", "user-12"],
    createdAt: "2024-09-20T00:00:00Z",
    updatedAt: "2024-11-05T00:00:00Z",
  },
  {
    id: "proj-1-sub-40",
    name: "Internationalization",
    description: "Multi-language support i18n",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-47",
    status: "active",
    teamIds: ["user-3", "user-7", "user-8"],
    createdAt: "2024-09-25T00:00:00Z",
    updatedAt: "2024-11-04T00:00:00Z",
  },
  {
    id: "proj-1-sub-41",
    name: "Accessibility Audit",
    description: "WCAG 2.1 compliance audit",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-51",
    status: "active",
    teamIds: ["user-3", "user-5", "user-13"],
    createdAt: "2024-10-01T00:00:00Z",
    updatedAt: "2024-11-03T00:00:00Z",
  },
  {
    id: "proj-1-sub-42",
    name: "UX Research",
    description: "User experience research and testing",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-56",
    status: "active",
    teamIds: ["user-3", "user-6", "user-7"],
    createdAt: "2024-10-05T00:00:00Z",
    updatedAt: "2024-11-02T00:00:00Z",
  },
  {
    id: "proj-1-sub-43",
    name: "Design System",
    description: "Component library and design system",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-14",
    status: "active",
    teamIds: ["user-3", "user-6", "user-7"],
    createdAt: "2024-10-10T00:00:00Z",
    updatedAt: "2024-11-01T00:00:00Z",
  },
  {
    id: "proj-1-sub-44",
    name: "Storybook Setup",
    description: "Storybook component documentation",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-24",
    status: "active",
    teamIds: ["user-3", "user-7", "user-8"],
    createdAt: "2024-10-15T00:00:00Z",
    updatedAt: "2024-10-31T00:00:00Z",
  },
  {
    id: "proj-1-sub-45",
    name: "Testing Framework",
    description: "Jest, Cypress setup and configuration",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-29",
    status: "active",
    teamIds: ["user-3", "user-5", "user-13"],
    createdAt: "2024-10-20T00:00:00Z",
    updatedAt: "2024-10-30T00:00:00Z",
  },
  {
    id: "proj-1-sub-46",
    name: "Code Quality Tools",
    description: "ESLint, Prettier, and SonarQube setup",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-38",
    status: "active",
    teamIds: ["user-3", "user-9", "user-11"],
    createdAt: "2024-10-25T00:00:00Z",
    updatedAt: "2024-10-29T00:00:00Z",
  },
  {
    id: "proj-1-sub-47",
    name: "Version Control",
    description: "Git workflow and branching strategy",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-42",
    status: "active",
    teamIds: ["user-3", "user-9", "user-10"],
    createdAt: "2024-10-30T00:00:00Z",
    updatedAt: "2024-10-28T00:00:00Z",
  },
  {
    id: "proj-1-sub-48",
    name: "Code Review Process",
    description: "Pull request review standards",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-47",
    status: "active",
    teamIds: ["user-3", "user-11", "user-12"],
    createdAt: "2024-11-01T00:00:00Z",
    updatedAt: "2024-10-27T00:00:00Z",
  },
  {
    id: "proj-1-sub-49",
    name: "Documentation Standards",
    description: "Code documentation best practices",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-51",
    status: "active",
    teamIds: ["user-3", "user-7", "user-8"],
    createdAt: "2024-11-05T00:00:00Z",
    updatedAt: "2024-10-26T00:00:00Z",
  },
  {
    id: "proj-1-sub-50",
    name: "Team Collaboration",
    description: "Team communication and collaboration tools",
    workspaceId: "ws-1",
    parentProjectId: "proj-1",
    managerId: "user-56",
    status: "active",
    teamIds: ["user-3", "user-9", "user-10"],
    createdAt: "2024-11-10T00:00:00Z",
    updatedAt: "2024-10-25T00:00:00Z",
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: "audit-1",
    workspaceId: "ws-1",
    projectId: "proj-1",
    userId: "user-1",
    action: "created",
    module: "project",
    resourceId: "proj-1",
    resourceName: "E-Commerce Platform v2",
    changes: { name: "E-Commerce Platform v2", status: "active" },
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "audit-2",
    workspaceId: "ws-1",
    projectId: "proj-1",
    userId: "user-3",
    action: "updated",
    module: "project",
    resourceId: "proj-1",
    resourceName: "E-Commerce Platform v2",
    changes: { description: "Updated description" },
    createdAt: "2024-03-15T14:30:00Z",
  },
  {
    id: "audit-3",
    workspaceId: "ws-1",
    projectId: "proj-1",
    userId: "user-1",
    action: "created",
    module: "document",
    resourceId: "doc-1",
    resourceName: "Product Requirements Document",
    changes: { name: "Product Requirements Document", category: "PRD" },
    createdAt: "2024-03-20T09:15:00Z",
  },
  {
    id: "audit-4",
    workspaceId: "ws-1",
    projectId: "proj-1",
    userId: "user-3",
    action: "created",
    module: "story",
    resourceId: "story-1",
    resourceName: "User Authentication via OAuth",
    changes: { title: "User Authentication via OAuth", status: "draft" },
    createdAt: "2024-04-01T11:20:00Z",
  },
  {
    id: "audit-5",
    workspaceId: "ws-1",
    projectId: "proj-1",
    userId: "user-5",
    action: "updated",
    module: "story",
    resourceId: "story-1",
    resourceName: "User Authentication via OAuth",
    changes: { status: "approved" },
    createdAt: "2024-04-05T16:45:00Z",
  },
  {
    id: "audit-6",
    workspaceId: "ws-1",
    projectId: "proj-1",
    userId: "user-1",
    action: "created",
    module: "testcase",
    resourceId: "test-1",
    resourceName: "Positive Login Flow",
    changes: { title: "Positive Login Flow", priority: "high" },
    createdAt: "2024-04-10T13:00:00Z",
  },
  {
    id: "audit-7",
    workspaceId: "ws-1",
    projectId: "proj-2",
    userId: "user-1",
    action: "created",
    module: "project",
    resourceId: "proj-2",
    resourceName: "Mobile Banking App",
    changes: { name: "Mobile Banking App", status: "active" },
    createdAt: "2024-06-15T10:00:00Z",
  },
  {
    id: "audit-8",
    workspaceId: "ws-1",
    projectId: "proj-2",
    userId: "user-3",
    action: "updated",
    module: "document",
    resourceId: "doc-20",
    resourceName: "Mobile App Architecture",
    changes: { status: "approved" },
    createdAt: "2024-06-20T14:30:00Z",
  },
  {
    id: "audit-9",
    workspaceId: "ws-1",
    projectId: "proj-2",
    userId: "user-5",
    action: "created",
    module: "testrun",
    resourceId: "run-1",
    resourceName: "Sprint 1 Testing",
    changes: { name: "Sprint 1 Testing", status: "pending" },
    createdAt: "2024-07-01T09:00:00Z",
  },
  {
    id: "audit-10",
    workspaceId: "ws-1",
    projectId: "proj-2",
    userId: "user-1",
    action: "updated",
    module: "testrun",
    resourceId: "run-1",
    resourceName: "Sprint 1 Testing",
    changes: { status: "completed", passedTests: 45, failedTests: 3 },
    createdAt: "2024-07-15T17:00:00Z",
  },
  ...Array.from({ length: 90 }, (_, i) => {
    const index = i + 11
    const actions = ["created", "updated", "deleted", "approved", "rejected"]
    const modules = ["project", "document", "story", "testcase", "testrun"]
    const users = ["user-1", "user-3", "user-5", "user-7", "user-9", "user-14", "user-24", "user-29"]
    const projects = ["proj-1", "proj-2"]

    const action = actions[index % actions.length]
    const module = modules[index % modules.length]
    const userId = users[index % users.length]
    const projectId = projects[index % projects.length]

    const resourceNames = {
      project: ["E-Commerce Platform v2", "Mobile Banking App", "SaaS Analytics Platform", "Healthcare Portal"],
      document: [
        "PRD Document",
        "Design Specifications",
        "Architecture Guide",
        "API Documentation",
        "Testing Strategy",
      ],
      story: [
        "User Authentication",
        "Payment Integration",
        "Dashboard Widget",
        "Search Functionality",
        "Notification System",
      ],
      testcase: ["Login Flow", "Payment Processing", "Data Validation", "Error Handling", "Performance Test"],
      testrun: ["Sprint 1 Testing", "UAT Round 1", "Regression Testing", "Smoke Testing", "End-to-End Testing"],
    }

    const names = resourceNames[module as keyof typeof resourceNames]
    const resourceName = names[index % names.length]

    const date = new Date(2024, 2 + (index % 10), (index % 28) + 1, index % 24, index % 60, 0)

    return {
      id: `audit-${index}`,
      workspaceId: "ws-1",
      projectId,
      userId,
      action: action as "created" | "updated" | "deleted" | "approved" | "rejected",
      module: module as "project" | "document" | "story" | "testcase" | "testrun",
      resourceId: `${module}-${index}`,
      resourceName,
      changes: {
        field: action === "created" ? "name" : "status",
        value: action === "created" ? resourceName : ["draft", "approved", "published", "completed"][index % 4],
      },
      createdAt: date.toISOString(),
    }
  }),
]

export const mockDocuments: Document[] = [
  {
    id: "doc-1",
    projectId: "proj-1",
    name: "Product Requirements Document",
    category: "PRD",
    content: "Comprehensive product requirements for e-commerce platform redesign",
    status: "approved",
    uploadedBy: "user-1",
    fileName: "PRD.pdf",
    fileType: "application/pdf",
    fileSize: 2500000,
    ragStatus: "ingested",
    versions: [],
    createdAt: "2024-03-20T09:15:00Z",
    updatedAt: "2024-04-01T10:30:00Z",
  },
  ...Array.from({ length: 49 }, (_, i) => ({
    id: `doc-${i + 2}`,
    projectId: i % 2 === 0 ? "proj-1" : "proj-2",
    name: `Document ${i + 2}: ${["Requirements", "Design", "Architecture", "Specification", "Analysis", "Report", "Plan", "Guide", "Manual", "Checklist"][i % 10]}`,
    category: ["PRD", "Design", "Architecture", "Specification", "Other"][i % 5],
    content: `Content for document ${i + 2}`,
    status: ["draft", "review", "approved"][i % 3],
    uploadedBy: `user-${(i % 50) + 1}`,
    fileName: `Document_${i + 2}.${["pdf", "docx", "xlsx", "txt"][i % 4]}`,
    fileType: [
      "application/pdf",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "text/plain",
    ][i % 4],
    fileSize: 1000000 + i * 50000,
    ragStatus: i % 2 === 0 ? "ingested" : "pending",
    versions: [],
    createdAt: new Date(Date.now() - (49 - i) * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - (49 - i) * 12 * 60 * 60 * 1000).toISOString(),
  })),
]

export const mockStories: UserStory[] = [
  {
    id: "story-1",
    projectId: "proj-1",
    title: "User Authentication via OAuth",
    description: "As a user, I want to authenticate using OAuth providers so that I can quickly access the platform",
    acceptanceCriteria: ["Support Google OAuth", "Support GitHub OAuth", "Handle OAuth errors"],
    status: "approved",
    priority: "high",
    linkedDocIds: ["doc-1"],
    linkedTestIds: ["test-1"],
    versions: [],
    comments: [],
    activities: [],
    createdBy: "user-3",
    createdAt: "2024-04-01T11:20:00Z",
    updatedAt: "2024-04-05T16:45:00Z",
  },
  ...Array.from({ length: 49 }, (_, i) => ({
    id: `story-${i + 2}`,
    projectId: i % 2 === 0 ? "proj-1" : "proj-2",
    title: `User Story ${i + 2}: ${["Create", "Update", "Delete", "View", "Export", "Import", "Search", "Filter", "Sort", "Share"][i % 10]} Feature`,
    description: `As a user, I want to ${["create", "update", "delete", "view", "export", "import", "search", "filter", "sort", "share"][i % 10]} so that I can ${["improve productivity", "manage data", "save time", "organize better", "collaborate", "track progress", "ensure compliance"][i % 8]}`,
    acceptanceCriteria: [
      `Criteria ${i + 2}-A: Feature works correctly`,
      `Criteria ${i + 2}-B: User can perform action`,
      `Criteria ${i + 2}-C: Validation works`,
    ],
    status: ["draft", "in_review", "approved", "published"][i % 4],
    priority: ["low", "medium", "high", "critical"][i % 4],
    linkedDocIds: [`doc-${(i % 50) + 1}`],
    linkedTestIds: [`test-${(i % 50) + 1}`],
    versions: [],
    comments: [],
    activities: [],
    createdBy: `user-${(i % 50) + 3}`,
    createdAt: new Date(Date.now() - (49 - i) * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - (49 - i) * 12 * 60 * 60 * 1000).toISOString(),
  })),
]

export const mockTestSuites: TestSuite[] = [
  {
    id: "suite-1",
    projectId: "proj-1",
    name: "Authentication Test Suite",
    description: "Test suite for authentication features",
    testIds: ["test-1", "test-2"],
    createdAt: "2024-04-10T10:00:00Z",
    updatedAt: "2024-04-15T14:00:00Z",
  },
  ...Array.from({ length: 49 }, (_, i) => ({
    id: `suite-${i + 2}`,
    projectId: i % 2 === 0 ? "proj-1" : "proj-2",
    name: `Test Suite ${i + 2}: ${["Authentication", "Authorization", "Payment", "Search", "Filter", "Export", "Import", "Validation", "Performance", "Security"][i % 10]}`,
    description: `Comprehensive test suite for ${["authentication", "authorization", "payment", "search", "filter", "export", "import", "validation", "performance", "security"][i % 10]} features`,
    testIds: Array.from({ length: 3 }, (_, j) => `test-${(i * 3) + j + 1}`),
    createdAt: new Date(Date.now() - (49 - i) * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - (49 - i) * 12 * 60 * 60 * 1000).toISOString(),
  })),
]

export const mockTestCases: TestCase[] = [
  {
    id: "test-1",
    projectId: "proj-1",
    suiteId: "suite-1",
    title: "Positive Login Flow",
    description: "Verify user can login with valid credentials",
    preconditions: "User account exists",
    steps: [{ id: "s1", order: 1, action: "Navigate to login page", expectedResult: "Login form displayed" }],
    expectedResult: "User successfully logged in",
    priority: "high",
    status: "active",
    versions: [],
    createdBy: "user-1",
    createdAt: "2024-04-10T13:00:00Z",
    updatedAt: "2024-04-12T09:30:00Z",
  },
  ...Array.from({ length: 49 }, (_, i) => ({
    id: `test-${i + 2}`,
    projectId: i % 2 === 0 ? "proj-1" : "proj-2",
    suiteId: `suite-${(i % 50) + 1}`,
    title: `Test Case ${i + 2}: ${["Positive", "Negative", "Edge", "Boundary", "Integration", "Performance", "Security", "Regression", "Smoke", "Sanity"][i % 10]} Flow`,
    description: `Test to verify ${["positive", "negative", "edge case", "boundary", "integration", "performance", "security", "regression", "smoke", "sanity"][i % 10]} behavior`,
    preconditions: `Setup required for test ${i + 2}`,
    steps: [
      { id: `s${i}-1`, order: 1, action: `Step 1 for test ${i + 2}`, expectedResult: "Expected outcome 1" },
      { id: `s${i}-2`, order: 2, action: `Step 2 for test ${i + 2}`, expectedResult: "Expected outcome 2" },
    ],
    expectedResult: `Test ${i + 2} should complete successfully`,
    priority: ["low", "medium", "high", "critical"][i % 4],
    status: ["draft", "active", "deprecated"][i % 3],
    versions: [],
    createdBy: `user-${(i % 50) + 3}`,
    createdAt: new Date(Date.now() - (49 - i) * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - (49 - i) * 12 * 60 * 60 * 1000).toISOString(),
  })),
]

export const mockTestRuns: TestRun[] = [
  {
    id: "run-1",
    projectId: "proj-1",
    name: "Sprint 1 Testing",
    testIds: ["test-1"],
    results: [{ testId: "test-1", status: "passed" }],
    status: "completed",
    createdBy: "user-5",
    createdAt: "2024-04-20T10:00:00Z",
  },
  ...Array.from({ length: 49 }, (_, i) => ({
    id: `run-${i + 2}`,
    projectId: i % 2 === 0 ? "proj-1" : "proj-2",
    name: `Test Run ${i + 2}: Sprint ${Math.floor(i / 10) + 1}`,
    testIds: Array.from({ length: 5 }, (_, j) => `test-${(i * 5) + j + 1}`),
    results: Array.from({ length: 5 }, (_, j) => ({
      testId: `test-${(i * 5) + j + 1}`,
      status: ["passed", "failed", "skipped"][Math.floor(Math.random() * 3)],
    })),
    status: ["pending", "in_progress", "completed"][i % 3],
    createdBy: `user-${(i % 50) + 5}`,
    createdAt: new Date(Date.now() - (49 - i) * 24 * 60 * 60 * 1000).toISOString(),
  })),
]

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    userId: "user-1",
    title: "Project Created",
    message: "E-Commerce Platform v2 project has been created",
    type: "info",
    read: false,
    createdAt: "2024-03-01T10:00:00Z",
  },
  ...Array.from({ length: 49 }, (_, i) => ({
    id: `notif-${i + 2}`,
    userId: `user-${(i % 56) + 1}`,
    title: `${["Project", "Document", "Story", "Test Case", "Team", "Comment", "Assignment"][i % 7]} Notification ${i + 2}`,
    message: `${["Created", "Updated", "Deleted", "Assigned", "Commented", "Approved", "Rejected"][i % 7]} by user for item ${i + 2}`,
    type: ["info", "warning", "success", "error"][i % 4],
    read: i % 2 === 0,
    createdAt: new Date(Date.now() - (49 - i) * 24 * 60 * 60 * 1000).toISOString(),
  })),
]

export const mockProjectMembers: ProjectMember[] = [
  {
    id: "pm-1",
    projectId: "proj-1",
    userId: "user-3",
    role: "pm",
    addedAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "pm-2",
    projectId: "proj-1",
    userId: "user-4",
    role: "ba",
    addedAt: "2024-03-02T00:00:00Z",
  },
  ...Array.from({ length: 48 }, (_, i) => ({
    id: `pm-${i + 3}`,
    projectId: i % 2 === 0 ? "proj-1" : "proj-2",
    userId: `user-${(i % 56) + 1}`,
    role: ["pm", "ba", "qa", "developer"][i % 4],
    addedAt: new Date(Date.now() - (48 - i) * 24 * 60 * 60 * 1000).toISOString(),
  })),
]
